version: '3.8'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backend_stag
        ports:
            - 2222:2222
        env_file:
            - ./backend/.env
        environment:
            - MONGODB_URI=mongodb://mongodb:27017/test
            - REDISCLOUD_URL=redis://redis:6379
        depends_on:
            - mongodb
            - redis
    mongodb:
        image: mongo:7.0.9
        ports:
            - 27017:27017
        volumes:
            - data:/data/db
        restart: unless-stopped
    redis:
        image: redis
        environment:
            - PUID=1000
            - PGID=1000
        ports:
            - 6379:6379
        restart: unless-stopped

volumes:
    data:
