version: '3.8'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - VITE_BASE_URL=http://localhost:2222
                - VITE_CLOUDINARY_CLOUD_NAME=novel.systems-dev
                - VITE_AUTH0_DOMAIN=novel-systems.eu.auth0.com
                - VITE_AUTH0_CLIENT_ID=aGQtv9eM6yWOsMBfn9TMr6gLyxyvCoGp
                - VITE_IS_DEBUG=false
        container_name: backend_stag
        ports:
            - 2222:2222
        env_file:
            - ./backend/.env
        environment:
            - NODE_ENV=production
            - MONGODB_URI=mongodb://mongodb:27017/test
            - REDISCLOUD_URL=redis://redis:6379
        depends_on:
            - mongodb
            - redis
    mongodb:
        image: mongo:7.0.9
        ports:
            - 27017:27017
        volumes:
            - data:/data/db
        restart: unless-stopped
    redis:
        image: redis
        environment:
            - PUID=1000
            - PGID=1000
        ports:
            - 6379:6379
        restart: unless-stopped

volumes:
    data:
