version: '3.8'
services:
    mongodb:
        image: mongo:5.0.26
        container_name: mongodb_stag
        ports:
            - 27017:27017
        volumes:
            - data:/data/db
        restart: unless-stopped
    redis:
        image: redis
        container_name: redis_stag
        environment:
            - PUID=1000
            - PGID=1000
        ports:
            - 6379:6379
        restart: unless-stopped

volumes:
    data:
